name: Feature Request
description: Request a new feature to add to War of Legends.
labels: ['enhancement']
assignees: ['knyghtmare']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the desired feature
      description: |
        Try to explain the desired end result, rather than speculating about how the feature could be implemented.
        If applicable, add screenshots or mockups to help explain your request.
    validations:
      required: true